spring:
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
storage:
  upload-dir: upload_dir_11
  max-files-to-store: 2
