spring:
  profiles:
    #Prifile is defined in PdfReaderApplication.kt (main)
    #active: h2database
    #active: filestorage
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
storage:
  max-files-to-store: 2
